version: '3'

services:
  frontend:
    build: frontend
    ports:
      - 8503:8501
    depends_on:
      - backend
    volumes:
        - ./storage:/storage
    volumes:
        - ./frontend:/app
  backend:
    build: backend
    ports:
      - 8088:8080
    volumes:
      - ./storage:/storage
    volumes:
      - ./backend:/app
